/** @file

Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this
  list of conditions and the following disclaimer in the documentation and/or
  other materials provided with the distribution.
* Neither the name of Intel Corporation nor the names of its contributors may
  be used to endorse or promote products derived from this software without
  specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
  THE POSSIBILITY OF SUCH DAMAGE.

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __FSPMUPD_H__
#define __FSPMUPD_H__

#include <FspUpd.h>

#pragma pack(1)


/** FSP-M Configuration
**/
typedef struct {

/** Offset 0x003F - Tseg Size
  Size of SMRAM memory reserved.
  2:2 MB, 4:4 MB, 8:8 MB, 16:16 MB
**/
  UINT8                       PcdSmmTsegSize;

/** Offset 0x0040 - MRC Debug Print Level
  Select the FSP MRC debug message print level. Options are a bitmask, so you can
  combine options. BIT0:MIN DEBUG, BIT1:MAX DEBUG, BIT2:TRACE, BIT3:MEM TRAIN, BIT4:TEST,
  BIT5:CPGC, BIT6:REG ACCESS
**/
  UINT8                       PcdFspMrcDebugPrintErrorLevel;

/** Offset 0x0041 - KTI Debug Print Level
  Select the FSP KTI debug message print level. Options are a bitmask, so you can
  combine options. BIT0:ERROR, BIT1:WARNING, BIT2:INFO0, BIT3:INFO1
**/
  UINT8                       PcdFspKtiDebugPrintErrorLevel;

/** Offset 0x0042 - Channel 0 DIMM 0 SPD SMBus Address
  SPD SMBus Address of each DIMM slot.
**/
  UINT8                       PcdSpdSmbusAddress_0_0;

/** Offset 0x0043 - Channel 0 DIMM 1 SPD SMBus Address
  SPD SMBus Address of each DIMM slot.
**/
  UINT8                       PcdSpdSmbusAddress_0_1;

/** Offset 0x0044 - Channel 1 DIMM 0 SPD SMBus Address
  SPD SMBus Address of each DIMM slot.
**/
  UINT8                       PcdSpdSmbusAddress_1_0;

/** Offset 0x0045 - Channel 1 DIMM 1 SPD SMBus Address
  SPD SMBus Address of each DIMM slot.
**/
  UINT8                       PcdSpdSmbusAddress_1_1;

/** Offset 0x0046 - Enable Rank Margin Tool
  Enable/disable Rank Margin Tool.
  $EN_DIS
**/
  UINT8                       PcdMrcRmtSupport;

/** Offset 0x0047 - RMT CPGC exp_loop_cnt
  Set the CPGC exp_loop_cnt field for RMT execution 2^(exp_loop_cnt -1).
  1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7, 8:8, 9:9, 10:10, 11:11, 12:12, 13:13, 14:14, 15:15
**/
  UINT8                       PcdMrcRmtCpgcExpLoopCntValue;

/** Offset 0x0048 - RMT CPGC num_bursts
  Set the CPGC num_bursts field for RMT execution 2^(num_bursts -1).
  1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7, 8:8, 9:9, 10:10, 11:11, 12:12, 13:13, 14:14, 15:15
**/
  UINT8                       PcdMrcRmtCpgcNumBursts;

/** Offset 0x0049 - Preserve Memory Across Reset
  Enable/disable memory preservation across reset.
  $EN_DIS
**/
  UINT8                       PcdMemoryPreservation;

/** Offset 0x004A - Fast Boot
  Enable/disable Fast Boot function. Once enabled, all following boots will use the
  presaved MRC data to improve the boot performance.
  $EN_DIS
**/
  UINT8                       PcdFastBoot;

/** Offset 0x004B - ECC Support
  Enable/disable ECC Support.
  $EN_DIS
**/
  UINT8                       PcdEccSupport;

/** Offset 0x004C - HSUART Device
  Select the PCI High Speed UART Device for Serial Port.
  0:HSUART0, 1:HSUART1, 2:HSUART2
**/
  UINT8                       PcdHsuartDevice;

/** Offset 0x004D - Memory Down
  Enable/disable Memory Down function.
  $EN_DIS
**/
  UINT8                       PcdMemoryDown;

/** Offset 0x004E
**/
  UINT32                      PcdMemoryDownConfigPtr;

/** Offset 0x0052 - SATA Controller 0
  Enable/disable SATA Controller 0.
  $EN_DIS
**/
  UINT8                       PcdEnableSATA0;

/** Offset 0x0053 - SATA Controller 1
  Enable/disable SATA Controller 1.
  $EN_DIS
**/
  UINT8                       PcdEnableSATA1;

/** Offset 0x0054 - Intel Quick Assist Technology
  Enable/disable Intel Quick Assist Technology.
  $EN_DIS
**/
  UINT8                       PcdEnableIQAT;

/** Offset 0x0055 - SPD Write Disable
  Select SMBus SPD Write Enable State (Default: 0 = [FORCE_ENABLE], 1 = [FORCE_DISABLE])
  0:Force Enable, 1:Force Disable
**/
  UINT8                       PcdSmbusSpdWriteDisable;

/** Offset 0x0056 - ME_SHUTDOWN Message
  Enable/Disable sending ME_SHUTDOWN message to ME, refer to FSP Integration Guide
  for details.
  $EN_DIS
**/
  UINT8                       PcdEnableMeShutdown;

/** Offset 0x0057 - XHCI Controller
  Enable / Disable XHCI controller
  $EN_DIS
**/
  UINT8                       PcdEnableXhci;

/** Offset 0x0058 - Memory Frequency
  Set DDR Memory Frequency, refer to FSP Integration Guide for details..
  15:Auto, 3:1600, 4:1866, 5:2133, 6:2400
**/
  UINT8                       PcdDdrFreq;

/** Offset 0x0059 - MMIO Size
  Set memory mapped IO space size
  0:2048M, 1:1024M, 2:3072M
**/
  UINT8                       PcdMmioSize;

/** Offset 0x005A
**/
  UINT8                       UnusedUpdSpace0[6];

/** Offset 0x0060 - Customer Revision
  The Customer can set this revision string for their own purpose.
**/
  UINT8                       PcdCustomerRevision[32];

/** Offset 0x0080 - 32-Bit bus mode
  Enable/Disable 32-Bit bus memory mode.
  $EN_DIS
**/
  UINT8                       PcdHalfWidthEnable;

/** Offset 0x0081 - TCL Performance
  Enable/Disable Tcl timing for performance.
  $EN_DIS
**/
  UINT8                       PcdTclIdle;

/** Offset 0x0082 - Interleave Mode
  Select Interleave Mode
  0:DISABLED, 1:MODE0, 2:MODE1, 3:MODE2
**/
  UINT8                       PcdInterleaveMode;

/** Offset 0x0083 - Memory Thermal Throttling
  Enable/disable Memory Thermal Throttling management mode
  $EN_DIS
**/
  UINT8                       PcdMemoryThermalThrottling;

/** Offset 0x0084
**/
  UINT8                       UnusedUpdSpace1[348];

/** Offset 0x01E0
**/
  UINT8                       ReservedMemoryInitUpd[16];
} FSP_M_CONFIG;

/** Fsp M UPD Configuration
**/
typedef struct {

/** Offset 0x0000
**/
  FSP_UPD_HEADER              FspUpdHeader;

/** Offset 0x0020
**/
  FSPM_ARCH_UPD               FspmArchUpd;

/** Offset 0x003F
**/
  FSP_M_CONFIG                 FspmConfig;

/** Offset 0x01F0
**/
  UINT8                       UnusedUpdSpace2[14];

/** Offset 0x01FE
**/
  UINT16                      UpdTerminator;
} FSPM_UPD;

#pragma pack()

#endif
